//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogUpp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Post
    {
        public int BlogID { get; set; }

        [Required(ErrorMessage = "Title is required (max 50 signs)")]
        [StringLength(50, ErrorMessage = "50 sign MAX")]
        [MinLength(1)]

        public string BlogTitle { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime BlogPostedOn { get; set; }


        [Required(ErrorMessage = "BlogPost is required (max 2000 signs)")]
        [StringLength(2000, ErrorMessage = "2000 sign MAX")]
        [MinLength(1)]
        public string BlogPost { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
